### ISSUE TITLE
mac 机报错

### ISSUE THREAD

**Issue by ThirdPrince** [arloor/telegram-client#3]
java.lang.UnsatisfiedLinkError: no libtdjni in java.library.path: /Users/dangyc/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2015)
	at org.drinkless.tdlib.example.Example.<clinit>(Example.java:65)
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'org.drinkless.tdlib.TdApi$Object org.drinkless.tdlib.Client.nativeClientExecute(org.drinkless.tdlib.TdApi$Function)'
	at org.drinkless.tdlib.Client.nativeClientExecute(Native Method)
	at org.drinkless.tdlib.Client.execute(Client.java:83)
	at org.drinkless.tdlib.example.Example.main(Example.java:73

不知道该如何解决

**Comment by arloor** [comment]
<img width="646" alt="图片" src="https://user-images.githubusercontent.com/21768987/176421885-a9b90279-1c2a-4e6b-bfff-747ebcfd163a.png">
这个没做吧

**Comment by ThirdPrince** [comment]
嗯嗯，解决了。

**Comment by lvgang214** [comment]
我是mac 系统 按照官方文档生成了dll 但是执行官方的demo  Please enter phone number:  输入完以后 怎么无事发生呢

**Comment by arloor** [comment]
检查下代理？
另外+86手机号好像收不到电报短信了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [arloor/telegram-client] mac 机报错 (Issue #3)




 
我是mac 系统 按照官方文档生成了dll 但是执行官方的demo  Please enter phone number:  输入完以后 怎么无事发生呢

**Comment by lvgang214** [comment]
是代理的问题 我是设置的全局代理 但是没有效果 还是要代码里面配置下代理 谢了哥们

**Comment by top6668** [comment]
代码里怎么配置代理呢 问一下
